### ISSUE TITLE
Update "About" for Firefox Extension

### ISSUE THREAD

**Issue by kacrouse** [dannysummerlin/force-navigator#12]
Firefox requires a bit of extra configuration for the extension to fully function since it blocks a lot more by default.
1. go into about:preferences#privacy
2. click _Manage Permissions..._ under _Cookies and Site Data_
3. add the classic URL into the list of Exceptions
4. click _Save Changes_

I'm happy to submit a PR for this, but wasn't sure which file to update.

**Comment by dannysummerlin** [comment]
Hi there, I've made a bunch of updates and it has been 1000 years since you first submitted this (I'm slow), I've not run into this on the computers I've had Firefox on; can you double check that this is still going on and then we can look at how to fix it/warn about it?

**Comment by kacrouse** [comment]
Finally got around to testing, and it looks to no longer be an issue! Closing this out.
