### ISSUE TITLE
CSP Trusted Site Definition Not Needed?

### ISSUE THREAD

**Issue by kacrouse** [dannysummerlin/force-navigator#13]
It seems like the CSP Trusted Site Definition isn't needed for the extension to function as the description indicates...what was it that did not function when that wasn't added? It's possible I'm just unaware of what isn't working.

Only tested in Firefox, but this seems like something that wouldn't be browser dependent.

**Comment by dannysummerlinjstartorg** [comment]
Interesting, and since you mention it I haven't run into it in other environments, so I've moved that note toward the bottom and changed it to say "may" instead of "must", thanks for checking on that!
