### ISSUE TITLE
Navigating to "Profiles" (Setup > Manage Users > Profiles) leads user to dead link/404 page

### ISSUE THREAD

**Issue by nbrown30** [dannysummerlin/force-navigator#18]
### Expected Behavior

Searching for "profiles" (Setup > Manage Users > Profiles), should take me to the profiles page in Lightning Experience (Anticipated URL: `https://<salesforce-domain>/lightning/setup/Profiles/home`)

### Actual Behavior

Currently the navigator takes you to a dead link/404 page: 
`https://<salesforce-domain>/lightning/setup/EnhancedProfiles/home`

This occurs regardless of whether "Enable Improved Setup User Interface" is enabled or disabled in the org (Found under Setup > Customize > User Interface)

### Steps to Reproduce

1. Open the Navigator (CTRL+SHIFT+Space)
2. Type in "profiles", hit enter

**Comment by dannysummerlinjstartorg** [comment]
Just pushed 2.8.1 for Chrome that made this swap, good call!
