### ISSUE TITLE
Firefox - Issue with "All Sites" shortcut

### ISSUE THREAD

**Issue by DavidSmithnz** [dannysummerlin/force-navigator#19]
The link generated for the "All Sites" page gets the extension URL or something embedded in it? Didn't seem to happen in the chrome version, just the 
Example below.
https://xx.lightning.force.commoz-extension//2dd8a1de-7697-47f6-802b-4e6e7a7c36ca/_ui/networks/setup/SetupNetworksPage
![image](https://user-images.githubusercontent.com/5713587/135418966-6953c236-54f4-41a9-9ae3-68f440b9ca40.png)
![image](https://user-images.githubusercontent.com/5713587/135418994-1fe34835-9f8a-446e-8d9d-73eefb76ad46.png)

**Comment by dannysummerlin** [comment]
Thanks for bringing this up! It should be all fixed with the last few releases, but let me know if see anymore oddities
