### ISSUE TITLE
Navigator Bar is not working

### ISSUE THREAD

**Issue by ruthsharon** [dannysummerlin/force-navigator#21]
Not working on Classic or Lightning when clicking on Ctrl + Shift + Space on Sandbox.
Getting an error:
Uncaught TypeError: Cannot read properties of undefined (reading 'setBadgeText')
    at main (popup.js:7:23)
    at HTMLDocument.<anonymous> (popup.js:3:2)

**Comment by eperlmutter** [comment]
I am getting a similar error on Prod - New instance  - Uncaught TypeError: Cannot read properties of null (reading 'style')
    at <anonymous>:2:48 - Error on the below 

					document.getElementById("sfnav_searchBox").style.zIndex = 9999

**Comment by EulogioGallo** [comment]
Also getting this issue. I was a huge fan of this tool in Classic but have never gotten it to work in Lightning, unfortunately.

**Comment by dannysummerlinjstartorg** [comment]
Just submitted an update for the Chrome version to address both of these glitches, so hopefully y'all won't see that any more. Feel free to reopen if version 2.8.1 doesn't fix these things
