### ISSUE TITLE
Lightning Links no longer available or working

### ISSUE THREAD

**Issue by benji1304** [dannysummerlin/force-navigator#24]
@dannysummerlin - was a release rolled back recently? 

I had new links available that went directly to the correct Lightning pages but in the last day or so(?) they are no longer available,and nearly all links directl to the Classic pages instead

**Comment by benji1304** [comment]
Example
<img width="726" alt="image" src="https://user-images.githubusercontent.com/7213889/177692724-5ce95c02-a443-4487-b6c4-95e95cab127c.png">
I had an option of 'Flows' here which went to the lightning setup page, but this goes to the classic page instead

**Comment by dannysummerlin** [comment]
My bad - I had gotten a little too link-replacement happy on the last update, so I reshuffled things again and wouldn't you know it that one broke again. I walked back through it fixing that and doing some other little cleanups, pushing it now - it will be version 3.0.10, let me know if you run into any other broke things

**Comment by benji1304** [comment]
Thanks, @dannysummerlin 

I had a quick look on my prod org at the weekend and it was fine but checking through my sandbox this morning I'm getting redirected into classic still. I'm checking prod again now and it's directing into Classic still

Definitely on the new version too. 
<img width="206" alt="image" src="https://user-images.githubusercontent.com/7213889/178161919-ecf075a0-d552-4b13-98d3-3401118bce66.png">

**Comment by benji1304** [comment]
@dannysummerlin I think this is still an issue

**Comment by dannysummerlin** [comment]
Hi @benji1304, sugh, I'll have to dig deeper. It is mostly working for me, I think there was something like a caching issue at first for me, but it cleared up. Just to confirm, you're in Chrome?

**Comment by benji1304** [comment]
Yup, in Chrome. I'll try clearing clearing cache, etc again and see if it helps.

**Comment by dannysummerlin** [comment]
Okay, just pushed another update, 3.2.13, did some more sorting and cleaning hopefully we'll get it this time!

**Comment by benji1304** [comment]
Thanks Danny! I'll grab the update as soon as I see it hit the store.

**Comment by benji1304** [comment]
@dannysummerlin working great! thanks for all your help. ❤️ this extension
