### ISSUE TITLE
Navigator Bar does not work in specific org

### ISSUE THREAD

**Issue by VAscendedSaiyan** [dannysummerlin/force-navigator#29]
Sandbox and Production orgs do not show with sfnav all other functions work (they have custom domains)
![2023-01-17 01_22_57-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/25672035/212824828-c70202ad-369f-4415-8afa-bc8616207d71.png)

Dev org does show with sfnav all other functions work (no custom domains)
![2023-01-17 01_22_23-Home _ Salesforce](https://user-images.githubusercontent.com/25672035/212824843-eef4cb4f-858b-49cf-a537-ec0f9cbe7af6.png)

**Comment by dannysummerlinjstartorg** [comment]
Hi there, just pushed a huge rewrite to version 4.1.2, that should clear out the cobwebs but feel free to reopen this if it doesn't!

**Comment by VAscendedSaiyan** [comment]
Issue still persistent. Works in dev org with more security settings, but not in sandbox/production with less security settings. Both use enhanced domain

Sandbox/production does have a custom domain, but I made a CSP for the classic URL. Still no dice

DevOrg
![image](https://user-images.githubusercontent.com/25672035/235757891-7d2c160a-d4bf-40df-82c8-d8fcae34f8e7.png)

SandboxOrg
![image](https://user-images.githubusercontent.com/25672035/235757992-ea305372-e07d-47c9-afec-87691b676e62.png)
