### ISSUE TITLE
Issue still persistent. Works in dev org with more security settings, but not in sandbox/production with less security settings. Both use enhanced domain

### ISSUE THREAD

**Issue by VAscendedSaiyan** [dannysummerlin/force-navigator#31]
Issue still persistent. Works in dev org with more security settings, but not in sandbox/production with less security settings. Both use enhanced domain

Sandbox/production does have a custom domain, but I made a CSP for the classic URL. Still no dice

DevOrg
![image](https://user-images.githubusercontent.com/25672035/235757891-7d2c160a-d4bf-40df-82c8-d8fcae34f8e7.png)

SandboxOrg
![image](https://user-images.githubusercontent.com/25672035/235757992-ea305372-e07d-47c9-afec-87691b676e62.png)

_Originally posted by @VAscendedSaiyan in https://github.com/dannysummerlin/force-navigator/issues/29#issuecomment-1531980605_

**Comment by TomHamiltonSmarsh** [comment]
We are experiencing the same issue in our org.

**Comment by spavuna-mle** [comment]
Same. Any ideas @dannysummerlin?

**Comment by dannysummerlin** [comment]
Hi there, I've just moved countries so I'm behind on things. Can you try opening up the [developer console](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/What_are_browser_developer_tools) while in the instance that is throwing errors and see if there are any messages that stand out as being errors from Salesforce Navigator? We'll have to recreate the issue to get to the bottom of it I'm afraid.

**Comment by dannysummerlin** [comment]
I'm merging this into #34, the short version is that the security features do block getting the token, the only way around that would be an extensive login handler that I won't be able to add, but I can restore all but the custom objects functionality, will be coming soon
