### ISSUE TITLE
Missing urls

### ISSUE THREAD

**Issue by Damecek** [dannysummerlin/force-navigator#33]
Hi, after the last update I am missing few important navigation items:
- Feature Settings > Digital Experiences > All Sites - before I was able to get there by just typing `all site` but that is now not available
- Process Automation > Paused And Failed Flow Interviews - before I was able to get there by just typing `paused flow` but that is now not available

please make those available.

**Comment by dannysummerlinjstartorg** [comment]
Thanks for the heads up, I have fixed it with https://github.com/dannysummerlin/force-navigator/commit/64074178dcf137fbfa47290dec8bb9308ec795ef, so the next update I push out (which should be soon) will add those options.

**Comment by Damecek** [comment]
Hi @dannysummerlinjstartorg sorry to bother you but when are you planning to release this fix?
