### ISSUE TITLE
Getting "null" text in final URL for some core functions

### ISSUE THREAD

**Issue by davidchengIC** [dannysummerlin/force-navigator#35]
It seems that after the Winter 24 release in production, all object-related links are broken due to a "null" text value appearing in the URL.  By object-related links I mean [object] > Fields, [object] > Details, etc.  

Example:  my home URL is
https://acme.lightning.force.com/lightning/page/home

When I invoke the navigator and go to Setup > Accounts > Details, it goes to this URL:
https://acme.lightning.force.comnull/lightning/setup/ObjectManager/Account/Details/view

This occurs for any standard or custom object.

This is happening on both OS X 12.7 and Windows 11.  Chrome v. 118.0.5993.70

**Comment by benji1304** [comment]
I'm getting the same

**Comment by sap995** [comment]
Also getting the same. Not sure if it was from the extension update, or my org moving to winter 24 as they both happened on the same date.

**Comment by CamilleGuillory** [comment]
Same here

**Comment by dyncan** [comment]
Encountered the same error.

**Comment by uris-tools** [comment]
Hi @dannysummerlin and all,

I believe I have a fix for this issue.  Can't add a PR as I'm not a collaborator, but hopefully this will help:

As I understand it, due to race condition, the new createSObjectCommands() function that runs in the background, sometimes has no access to forceNavigator.serverUrl (as this value is set in the contentScript).

To fix it, I passed the value of serverUrl in the "getMetaData" message, in a similar way apiUrl and other values are passed.
The result is that the error is not happening anymore.

The changes are:
background.js:
```javascript
const parseMetadata = (data, url, settings, serverUrl = {})=>{                               <----------
	if (data.length == 0 || typeof data.sobjects == "undefined") return false
	let mapKeys = Object.keys(forceNavigator.objectSetupLabelsMap)
	return data.sobjects.reduce((commands, sObjectData) => forceNavigator.createSObjectCommands(commands, sObjectData, serverUrl), {})
}
```
shared.js:
```js
	"createSObjectCommands": (commands, sObjectData, serverUrl) => {             <----------
		const { labelPlural, label, name, keyPrefix } = sObjectData
		const mapKeys = Object.keys(forceNavigator.objectSetupLabelsMap)
		if (!keyPrefix || forceNavigatorSettings.skipObjects.includes(keyPrefix)) { return commands }
		let baseUrl = ""
		if (forceNavigatorSettings.lightningMode && name.endsWith("__mdt")) { baseUrl += "/lightning/setup/CustomMetadata/page?address=" }
		commands[keyPrefix + ".list"] = {
			"key": keyPrefix + ".list",
			"url": `${baseUrl}/${keyPrefix}`,
			"label": t("prefix.list") + " " + labelPlural
		}
		commands[keyPrefix + ".new"] = {
			"key": keyPrefix + ".new",
			"url": `${baseUrl}/${keyPrefix}/e`,
			"label": t("prefix.new") + " " + label
		}
		if(forceNavigatorSettings.lightningMode) {
			let targetUrl = serverUrl + "/lightning/setup/ObjectManager/" + name                 <----------
			mapKeys.forEach(key=>{
				commands[keyPrefix + "." + key] = {
					"key": keyPrefix + "." + key,
					"url": targetUrl + forceNavigator.objectSetupLabelsMap[key],
					"label": [t("prefix.setup"), label, t(key)].join(" > ")
				}
			})
		} else {
			// TODO maybe figure out how to get the url for Classic
			commands[t("prefix.setup") + label] = { "url": keyPrefix, "key": key}
		}
		return commands
```

```js
	"loadCommands": (settings, force = false) => {
		if(!forceNavigator.serverInstance || (!forceNavigatorSettings.sessionIdDisabled && [forceNavigator.sessionId, forceNavigator.organizationId].includes(null))) {
			return forceNavigator.init()
		}
		if(force || Object.keys(forceNavigator.commands).length === 0)
			forceNavigator.resetCommands()
		if(!forceNavigatorSettings.sessionIdDisabled) {
			let options = {
				"sessionHash": forceNavigator.sessionHash,
				"domain": forceNavigator.serverInstance,
				"apiUrl": forceNavigator.apiUrl,
				"key": forceNavigator.organizationId,
				"force": force,
				"sessionId": forceNavigator.sessionId,
				"serverUrl" : forceNavigator.serverUrl,                               <----------
				"action": "getMetadata"
			}
```


-Uri

**Comment by dannysummerlin** [comment]
@uris-tools  thanks for taking a look! I'm out and about today, but in the mean time you can fork the repo, make your edit, and then do a pull request, that will help keep track and highlight the exact changes even better - you only need to be a collaborator to give approval on a PR, but anyone can make one!
